### ISSUE TITLE
How to open pool liquidity using solathon?

### ISSUE THREAD

**Issue by l-arkadiy-l** [SuperteamDAO/solathon#85]
I have aim to open and close meteora.ag pools liquidity using solathon. I checked that I have transfer params in `from solathon.core.instructions import transfer` but I can't understand how using that to open pool liquidity. Can you please help me and tell is it possible to open pool liquidity using this library?

**Comment by GitBolt** [comment]
You cannot do that with Solathon since opening liquidity on Meteora requires interaction with their program, and Solathon does not support interaction with external programs. The `transfer` method that you see is only for SOL transferring from one account to another.

Unfortunately it appears that Meteora itself does not offer any Python SDK either to interact with their programs, they do have a TypeScript SDK: https://docs.meteora.ag/dlmm/dlmm-integration/dlmm-sdk

**Comment by l-arkadiy-l** [comment]
ok, thank's a lot
